export const data = [
	{
		image: "./TheUltimateGoogleAdsTrainingCourse.jpg",
		type: "Marketing",
		title: "The Ultimate Google Ads Training Course",
		price: 100,
		author: "Jerome Bell",
	},
	{
		image: "./PrductManagementFundamentals.jpg",
		type: "Management",
		title: "Prduct Management Fundamentals",
		price: 480,
		author: "Marvin McKinney",
	},
	{
		image: "./HRManagementandAnalytics.jpg",
		type: "HR & Recruting",
		title: "HR  Management and Analytics",
		price: 200,
		author: "Leslie Alexander Li",
	},
	{
		image: "./BrandManagementPRCommunications.jpg",
		type: "Marketing",
		title: "Brand Management & PR Communications",
		price: 530,
		author: "Kristin Watson",
	},
	{
		image: "./GraphicDesignBasic.jpg",
		type: "Design",
		title: "Graphic Design Basic",
		price: 500,
		author: "Guy Hawkins",
	},
	{
		image: "./BusinessDevelopmentManagement.jpg",
		type: "Management",
		title: "Business Development Management",
		price: 400,
		author: "Dianne Russell",
	},
	{
		image: "./HighloadSoftwareArchitecture.jpg",
		type: "Development",
		title: "Highload Software Architecture",
		price: 600,
		author: "Brooklyn Simmons",
	},
	{
		image: "./HumanResourcesSelectionandRecruitment.jpg",
		type: "HR & Recruting",
		title: "Human Resources – Selection and Recruitment",
		price: 150,
		author: "Kathryn Murphy",
	},
	{
		image: "./UserExperience.HumancenteredDesign.jpg",
		type: "Design",
		title: "User Experience. Human-centered Design",
		price: 240,
		author: "Cody Fisher",
	},
];
